"""Markdown rendering utilities for reports."""

from datetime import date
from typing import Any

from qi.models import RelevanceDigest
from qi.processing.features import FeatureSnapshot


def render_header(title: str, start_date: date, end_date: date) -> str:
    """Render report header."""
    return f"""# {title}

**Period**: {start_date} to {end_date}
**Generated**: {date.today()}

---
"""


def render_metrics_table(features: FeatureSnapshot) -> str:
    """Render core metrics as a markdown table."""
    lines = [
        "## Core Metrics",
        "",
        "| Metric | Value |",
        "|--------|-------|",
    ]
    
    if features.get("energy_mean") is not None:
        lines.append(f"| Energy (avg) | {features['energy_mean']:.1f} |")
    if features.get("mood_mean") is not None:
        lines.append(f"| Mood (avg) | {features['mood_mean']:.1f} |")
    if features.get("sleep_mean") is not None:
        lines.append(f"| Sleep (avg) | {features['sleep_mean']:.1f} |")
    if features.get("mood_volatility") is not None:
        lines.append(f"| Mood volatility | {features['mood_volatility']:.2f} |")
    
    lines.append("")
    return "\n".join(lines)


def render_events_section(features: FeatureSnapshot) -> str:
    """Render events section."""
    lines = [
        "## Events",
        "",
        f"- Wins: {features.get('win_count', 0)}",
        f"- Frictions: {features.get('friction_count', 0)}",
        f"- Insights: {features.get('insight_count', 0)}",
        "",
    ]
    return "\n".join(lines)


def render_tokens_section(features: FeatureSnapshot) -> str:
    """Render custom metrics section."""
    lines = [
        "## Custom Metrics",
        "",
    ]
    
    # Render any dynamically generated metric
    added = False
    for k, v in features.items():
        # Match keys that end with _total, _rate, _count to find dynamic metrics
        if k.endswith("_total"):
            lines.append(f"- {k.replace('_total', '')} (total): {v}")
            added = True
        elif k.endswith("_rate"):
            lines.append(f"- {k.replace('_rate', '')} (rate): {v:.0%}")
            added = True
        elif k.endswith("_count") and k not in ("win_count", "friction_count", "insight_count", "compulsion_event_count", "dci_count", "event_count"):
            lines.append(f"- {k.replace('_count', '')} (count): {v}")
            added = True
            
    if not added:
        lines.append("No custom metrics tracked.")
        
    lines.append("")
    return "\n".join(lines)


def render_delta_section(deltas: dict[str, Any]) -> str:
    """Render week-over-week deltas."""
    lines = [
        "## Week-over-Week Changes",
        "",
    ]
    
    # Core fixed labels
    delta_labels = {
        "energy_mean_delta": "Energy",
        "mood_mean_delta": "Mood",
        "sleep_mean_delta": "Sleep",
        "win_count_delta": "Wins",
        "friction_count_delta": "Frictions",
        "insight_count_delta": "Insights",
    }
    
    for key, value in deltas.items():
        if value is None:
            continue
            
        label = delta_labels.get(key)
        if not label:
            # Format dynamic labels (e.g. habit_1_count_delta -> Habit 1 count)
            label = key.replace("_delta", "").replace("_", " ").capitalize()
            
        sign = "+" if value > 0 else ""
        if isinstance(value, float):
            lines.append(f"- {label}: {sign}{value:.1f}")
        else:
            lines.append(f"- {label}: {sign}{value}")
            
    lines.append("")
    return "\n".join(lines)


def render_streak_section(features: FeatureSnapshot) -> str:
    """Render streak information."""
    lines = [
        "## Streaks",
        "",
    ]
    added = False
    for k, v in features.items():
        if k.endswith("_streak"):
            label = k.replace("_streak", "").replace("_", " ").capitalize()
            lines.append(f"- {label} streak: {v} days")
            added = True
            
    if not added:
        lines.append("No streaks tracked.")
        
    lines.append("")
    return "\n".join(lines)


def render_footer() -> str:
    """Render report footer."""
    return """---

*Generated by QI - Quality Intelligence*
"""


def digests_to_dicts(digest_models: list[RelevanceDigest]) -> list[dict[str, Any]]:
    """Convert relevance digest models to plain dict snapshots for prompts/artifacts."""
    return [
        {
            "item_type": digest.item_type,
            "source_ts": digest.source_ts.isoformat(),
            "principle_ids": digest.principle_ids,
            "kr_refs": digest.kr_refs,
            "digest": digest.digest,
            "citation": digest.citation,
        }
        for digest in digest_models
    ]
